### ISSUE TITLE
Changing ownership: Operation not permitted

### ISSUE THREAD

**Issue by dngray** [linuxserver/docker-sabnzbd#150]
## Expected Behavior
Start and allow setting of PUID/PGID.

## Current Behavior
Previous release [3.6.1-ls78](https://github.com/linuxserver/docker-sabnzbd/releases/tag/3.6.1-ls78) works just fine.

## Steps to Reproduce
1. Start instance with environmental variables:
   ```yaml
   environment:
   - PUID=1003
   - PGID=1004
   ```

## Environment
**OS:** Archlinux
**CPU architecture:** x86_64
**How docker service was installed:**
pacman

## Command used to create docker container (run/create/compose/screenshot)

```yaml
sabnzbd:
  extends:
    file: usenet_common.yml
    service: usenet_apps
  image: ghcr.io/linuxserver/sabnzbd
  container_name: sabnzbd
  network_mode: service:vpn_usenet
  volumes:
    - /mnt/container_data/sabnzbd:/config
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.sabnzbd.tls=true"
    - "traefik.http.routers.sabnzbd.entrypoints=websecure"
    - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.$MY_DOMAIN`)"
    - "traefik.http.services.sabnzbd.loadbalancer.server.port=6767"
  restart: unless-stopped

services:
  usenet_apps:
    environment:
      - PUID=1003
      - PGID=1004
      - TZ=${TZ}
    volumes:
      - xxxxxx
    restart: unless-stopped
```

## Docker logs
```
sabnzbd     | -------------------------------------
sabnzbd     | GID/UID
sabnzbd     | -------------------------------------
sabnzbd     | 
sabnzbd     | User uid:    1003
sabnzbd     | User gid:    1004
sabnzbd     | -------------------------------------
sabnzbd     | 
sabnzbd     | chown: changing ownership of '/config/custom-services.d.piF10oZt': Operation not permitted
sabnzbd     | chown: changing ownership of '/config/custom-cont-init.d.piF10oZt': Operation not permitted
sabnzbd     | s6-rc: warning: unable to start service init-sabnzbd-config: command exited 1
```

Nothing else is relevant there.
