### ISSUE TITLE
Startup broken with NFS config mount on 3.6.1 - Working on 3.6.0

### ISSUE THREAD

**Issue by JagerSprinkles** [linuxserver/docker-sabnzbd#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container should start up as normal not stopping upon chown errors as it has done in the past.

## Current Behavior

Container does not start up. Gives error on chown when trying to update folder on NFS. Seems to be a regression as it was functional before.
Downgrading to container version 3.6.0 it will start up with no issue at all. No settings or permissions changed. Has been running with this configuration for probably over a year. This issue is likely related to not allowing root user on my NFS share but there have been no issues until the latest update. Startup never used to fail on chown errors.

## Steps to Reproduce

1. Use container version 3.6.1
2. Have /config on NFS mount with correct permissions
3. Set PUID and GUID to match permissions of /config on the NFS mount
4. s6-rc errors out on chown command even though permissions are correct to begin with.

## Environment
**OS:** Debian 11.5
**CPU architecture:** x86_64
**How docker service was installed:** From the official docker repo

**Screenshot of permissions inside of container:**
![Screenshot 2022-10-12 172512](https://user-images.githubusercontent.com/6476475/195451005-4fdfc853-0b3a-416c-91d5-40e1b51ee225.jpg)

**Screenshot of permissions on NFS server:**
![Screenshot 2022-10-12 172749](https://user-images.githubusercontent.com/6476475/195451418-46624bd5-f968-4478-a333-765bd8385c17.jpg)
media user=8675309

## Command used to create docker container (run/create/compose/screenshot)

```
  nas-config-SABnzbd_vol:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.*.*.*,rw,noatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=1200,retrans=2,sec=sys,clientaddr=172.*.*.*,local_lock=none
      device: ":/****/****/apps/sabnzbd"

sabnzbd:
  image: lscr.io/linuxserver/sabnzbd:3.6.0
  #image: lscr.io/linuxserver/sabnzbd:3.6.1
  container_name: sabnzbd
  hostname: sabnzbd
  environment:
    - PUID=8675309
    - PGID=1000
    - TZ=America/New_York
    - LOG_LEVEL=warn
  volumes:
    - nas-config-SABnzbd_vol:/config
    - nas-SABnzbd_vol:/mnt/media/SABnzbd
    - 'nas-bp-large_media_vol:/mnt/large_media'
    - /mnt/disk2/sab-downloads:/downloads
  ports:
    - 8081:8080
    - 9090:9090
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '5'
        memory: 6942M
  logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "1m"
```

## Docker logs

**Log from 3.6.1:**
```
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
SABnzbd: https://sabnzbd.org/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    8675309
User gid:    1000
-------------------------------------

usermod: Failed to change ownership of the home directorychown: changing ownership of '/config': Operation not permitted
find: /config/admin/future: Permission denied
chown: changing ownership of '/config': Operation not permitted
chown: changing ownership of '/config/logs': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.log.3': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.log': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.log.4': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.log.5': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.error.log': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.log.2': Operation not permitted
chown: changing ownership of '/config/logs/sabnzbd.log.1': Operation not permitted
chown: changing ownership of '/config/admin': Operation not permitted
chown: changing ownership of '/config/admin/postproc2.sab': Operation not permitted
chown: changing ownership of '/config/admin/history1.db': Operation not permitted
chown: changing ownership of '/config/admin/future': Operation not permitted
chown: changing ownership of '/config/admin/Rating.sab': Operation not permitted
chown: changing ownership of '/config/admin/rss_data.sab': Operation not permitted
chown: changing ownership of '/config/admin/watched_data2.sab': Operation not permitted
chown: changing ownership of '/config/admin/totals10.sab': Operation not permitted
chown: changing ownership of '/config/admin/queue10.sab': Operation not permitted
chown: changing ownership of '/config/sabnzbd.ini.bak': Operation not permitted
chown: changing ownership of '/config/sabnzbd.ini': Operation not permitted
s6-rc: warning: unable to start service init-sabnzbd-config: command exited 1
```

**Log from 3.6.0 working correctly:**
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
SABnzbd: https://sabnzbd.org/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    8675309
User gid:    1000
-------------------------------------

usermod: Failed to change ownership of the home directorychown: changing ownership of '/config': Operation not permitted
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
mkdir: cannot create directory ‘/config/custom-cont-init.d’: Permission denied
mkdir: cannot create directory ‘/config/custom-services.d’: Permission denied
chown: cannot access '/config/custom-cont-init.d': No such file or directory
chown: cannot access '/config/custom-services.d': No such file or directory
cont-init: info: /etc/cont-init.d/90-custom-folders exited 1
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun sabnzbd (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started

```

Edit:
This error might be related to this line:
https://github.com/linuxserver/docker-sabnzbd/blob/b0e03dffff43d6da6b104b09d117c93cf95ff225/root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run#L13
Commit: https://github.com/linuxserver/docker-sabnzbd/commit/b0e03dffff43d6da6b104b09d117c93cf95ff225
