### ISSUE TITLE
Server not starting after update, port 8080 blocked

### ISSUE THREAD

**Issue by RafaelSchridi** [linuxserver/docker-sabnzbd#82]
Watchtower recently updated my version 3.0.0 and since then sabnzbd just won't start. All i get in the log is 
>Fatal error:, Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.

I tried changing the outgoing port in docker to 8081 and changing the config file to also use port 8081 but that did nothing since it's always forced to 8080.

here is my config
```
   sabnzbd:
        container_name: sabnzbd
        restart: unless-stopped
        volumes:
            - '/opt/x/settings/sabnzbd:/config'
            - '/zfs/x/Content/Complete:/downloads'
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe/Amsterdam
        ports:
            - '8080:8080'
        image: linuxserver/sabnzbd
        networks:
            net:
                ipv4_address: 172.50.0.100
```

It shares the network with other services but disabling those did nothing

```
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16
```
I have now returned to 2.3.9-0ubuntu1jcfp218.04-ls67

------------------------------

## Expected Behavior
I expect it to start and not complain about any used ports since it resides in a docker container.

## Current Behavior
Doesn't start due to the above mentioned error.

## Steps to Reproduce

1. run the docker compose file
2. look at logs
3. see it restarting

## Environment
**OS:** Arch      
**CPU architecture:** x86_64    
**How docker service was installed:** Composer file     

## Command used to create docker container (run/create/compose/screenshot)
sudo docker-compose pull && sudo docker-compose up -d --remove-orphans

## Docker logs
https://pastebin.com/raw/iY5vL4Vv

**Comment by aptalca** [comment]
It looks like sabnzbd keeps crashing. Look through the logs in the config folder to see if the reason is logged

**Comment by ajschroeder** [comment]
I am experiencing the same issue, watchtower upgraded sabnzbd to version 3, and it produces the following log output over and over:
```
sabnzbd      | Fatal error:
sabnzbd      |   Unable to bind to port 8080 on localhost. Some other software uses the port or SABnzbd is already running.
```

I am launching everything from a docker-compose file, here is my config:
```
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - /docker/containers/sabnzbd/config:/config
      - ./Download/Complete:/downloads
      - ./Download/Incomplete:/incomplete-downloads
    ports:
      - '8080:8080'
      - '9090:9090'
```

I have also reverted back to 2.3.9-0ubuntu1jcfp218.04-ls67 and it is running as expected. 

My server is x86_64 and runs Ubuntu 18.04. I would be glad to post any other relevant information but note that the sabnzbd.log file stopped being updated when the docker container was upgraded.
