### ISSUE TITLE
Notify.py & sabnzbd-notify.py wrapper failing with ModuleNotFoundError: No module named 'nzbget'

### ISSUE THREAD

**Issue by ceyounger** [linuxserver/docker-sabnzbd#87]
------------------------------

## Expected Behavior

Using Notify.py with the sabnzbd-notify.py wrapper from [caronc/nzb-notify](https://github.com/caronc/apprise) should send a post-processing notification to configured target.
## Current Behavior

Notify.py script (called by sabnzbd-notify.py) fails with the error:
```
# python sabnzbd-notify.py complete 'Hello' 'World' discord://XXXXXXXXXXX@XXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "/config/scripts/Notify.py", line 174, in <module>
    from nzbget import SCRIPT_MODE
ModuleNotFoundError: No module named 'nzbget'
```
## Steps to Reproduce

1. Download scripts and copy to sabnzbd/config/scripts
2. Configure and enable via Settings -> Notifications -> Notification Scripts
3. Click "Test Notification" button
4. Can also replicate using test script inside the container (as shown above)

## Environment
**OS:** Synology DSM 6.2x
**CPU architecture:** x86_64     
**How docker service was installed:**      

Synology Docker installed via Synology DSM packages version 18.09.8

## Command used to create docker container (run/create/compose/screenshot)

Used Portainer to launch sabnzbd via an imported docker-compose (version 2) into a Portainer Stack configuration:
```
version: '2'
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - XXXX:8080
      - XXXX:9090
    environment:
      - TZ=America/Los_Angeles
      - PGID=XXX
      - PUID=XXXX
    volumes:
      - XXXX/nzb:/downloads/nzb
      - XXXX:/downloads/complete
      - XXXX/nzbbackups:/sabnzbd/nzbbackups
      - XXXX/Incomplete:/downloads/incomplete
      - XXXX/sabnzbd:/config
      - XXXX/sabnzbd:/sabnzbd/config/scripts
    dns:
      - X.X.X.X
      - 1.1.1.1
      - 1.0.0.1
    dns_search: xxxx.xxx
    networks:
      - xxxxxxx

networks:
  xxxxxx:
    external:
      name: xxxxxx
```
## Docker logs

Truncated for brevity:
```
2020-09-02 23:42:04,732::ERROR::[notifier:361] Notification script returned exit code 1 and output "Traceback (most recent call last):
  File "/config/scripts/Notify.py", line 174, in <module>
    from nzbget import SCRIPT_MODE
ModuleNotFoundError: No module named 'nzbget'
```

## Workaround / Suggestion for fix
Needed to run `pip install pynzbget` inside container to restore functionality to script.  Suggest adding **pynzbget** to the Dockerfile pip module install array.
