### ISSUE TITLE
SABnzbd applying permissions to mounted volumes (incomplete-downloads and downloads)

### ISSUE THREAD

**Issue by jpdsc** [linuxserver/docker-sabnzbd#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When assigning a Temporary Download Folder and Completed Download Folder in SABnzbd, the original permissions should stay intact.

## Current Behavior
Whenever the container is created, SABnzbd applies permissions 755 to the folder set as Temporary Download Folder and Completed Download Folder and therefore overwriting any other permissions added to the folder.
I have cross-checked this with other download clients and none of them is doing this to the folders.

## Steps to Reproduce
1. Create Temporary Download Folder and Completed Download Folder 
2. Change the permissions to something different than 755
3. Run the container with the volumes mounted
4. Check the permissions `ls -ld `
5. The permission is now changed from the original permission to 755

## Environment
**OS:** Synology
**CPU:** architecture:** x86_64
**How docker service was installed:**
Synology package manager

## Command used to create docker container (run/create/compose/screenshot)
docker-compose:

```
    sabnzbd:
        container_name: SABnzbd
        environment:
            - TZ=Europe/Amsterdam
            - PGID=101
            - PUID=1026
        volumes:
            - '/volume2/docker/SABnzbd/config:/config:rw'
            - '/volume1/Shared:/shared' ## in the SABnzbd GUI I set the correct path
        networks:
            private:
                ipv4_address: 10.2.0.2
        hostname: NAS
        ports:
            - '8080:8080'
            - '9090:9090'
        restart: unless-stopped
        image: 'linuxserver/sabnzbd:latest'
```
## Docker logs
```
joao@NAS:/volume2/docker/Compose/Production$ ls -ld "/volume1/Shared/Downloading/"
drwxr-xr-x 1 joao administrators 0 Dec 23 10:51 /volume1/Shared/Downloading/
joao@NAS:/volume2/docker/Compose/Production$ ls -ld "/volume1/Shared/Downloads/Unsorted/"
drwxr-xr-x 1 joao administrators 0 Dec 23 10:32 /volume1/Shared/Downloads/Unsorted/
```

I have a thread with SABnzbd regarding this here: https://forums.sabnzbd.org/viewtopic.php?f=2&t=24696&p=123104#p123104

Is there anything I can do to resolve this? Or is it possible to resolve this through the container creation?
Edit: it seems to also change permission of the config folder to Everyone regardless if you chown it to a different user...
